### PR TITLE
Update App, Runtime and Shared Modules

### PR DESCRIPTION
**Pull request by joshuag1000**
Small patch to update flatpak's runtime and shared modules to the latest version

### CODE REVIEW

**Comment by joshuag1000** [comment]
bot, build

**Comment by joshuag1000** [comment]
bot, build

**Comment by nedrichards** [comment]
I'm seeing some issues with the SSH agent here and not reading the cursor theme. I need to try this on 21.08 to see if it's a runtime issue.

**Comment by joshuag1000** [comment]
> I'm seeing some issues with the SSH agent here and not reading the cursor theme. I need to try this on 21.08 to see if it's a runtime issue.

What kind of issues? 
If you see my attached screenshot you can see that everything appears to work fine for me.
My screenshot tool doesn't show my mouse cursor but that looks normal for me too.
image
image

**Comment by joshuag1000** [comment]
> I'm seeing some issues with the SSH agent here and not reading the cursor theme. I need to try this on 21.08 to see if it's a runtime issue.

Just so you know @nedrichards i have recently learned that the cursor theme is a known issue with the runtime (and a few other things i think) and so is not related to this app.

**Comment by nedrichards** [comment]
I've pushed a commit that addresses the issue in #83 (which would otherwise affect this release as well as it's a new linter) and reverts to 21.08 which in my local build removes the cursor regression and is still in security support.

I'm still having some issues connecting to the SSH agent using this version which aren't present in 3.60.2 it would appear that I'm not the only person seeing similar behaviour with SFTP https://trac.filezilla-project.org/ticket/12781 (although that's not exactly the same). I'll keep on digging.

**Comment by nedrichards** [comment]
bot, build

**Comment by joshuag1000** [comment]
> I've pushed a commit that addresses the issue in #83 (which would otherwise affect this release as well as it's a new linter) and reverts to 21.08 which in my local build removes the cursor regression and is still in security support.
> 
> I'm still having some issues connecting to the SSH agent using this version which aren't present in 3.60.2 it would appear that I'm not the only person seeing similar behaviour with SFTP https://trac.filezilla-project.org/ticket/12781 (although that's not exactly the same). I'll keep on digging.

Makes Sense.

**Pull request merged**
