### PR TITLE
Disable auto and manual update check

### LINKED ISSUE #48: Deactivate warning about new version being available
Hi,

Before yesterday update (#47), org.filezillaproject.Filezilla didn't stop warning me that a new version was available at each startup.

Since update are handled by Flatpak/Flathub and not directly by the application or by downloading an executable from the application website, such warnings are inappropriate and should be deactivated.

I've find that in org.filezillaproject.Filezilla, under Settings > Updates, Automatically check for updates was set on "once by day". I think that should be set on "never" by default.

Thanks

### PR DESCRIPTION
**Pull request by x80486**
According to this file: `https://svn.filezilla-project.org/svn/FileZilla3/trunk/configure.ac` (section: **Updatecheck related flags**), looks like playing with `disable-manualupdatecheck` and/or `disable-autoupdatecheck` should do the trick.

Closes #48

### CODE REVIEW

**Comment by x80486** [comment]
image

I don't see the `Check for updates...` option in the `Help` menu, so I would assume it should do it.

**Comment by x80486** [comment]
ping @nedrichards

**Comment by nedrichards** [comment]
Thanks for this, sorry not to see it over christmas. I've pulled these changes into the branch that updates to 3.52.0 https://github.com/flathub/org.filezillaproject.Filezilla/pull/57

**Comment by antistress** [comment]
Thanks !

**Pull request closed without merging**
