### PR TITLE
Update to 3.37.1

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by TingPing** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
@TingPing Should i update the screenshot too on the same PR? Btw, I would love to get write access to this repository as it's a tool I'm using daily and I would be able to keep it up to date. Thanks!

**Comment by TingPing** [comment]
> I would love to get write access to this repository as it's a tool I'm using daily and I would be able to keep it up to date

Invited.

> Should i update the screenshot too on the same PR?

Can just push that later now I suppose.

**Comment by bilelmoussaoui** [comment]
Already updated. Thanks @nedrichards

**Pull request closed without merging**
